name: huazhixia
description: A new Flutter project.
publish_to: 'none'

version: 2.2.1+7

environment:
  # sdk: '>=2.19.6 <3.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 本地化
  flutter_localizations:
    sdk: flutter

  # Cupertino图标
  cupertino_icons: ^1.0.2
  # 网络请求
  dio: 5.1.2
  # 状态管理
  provider: ^6.0.5
  # Remix图标库
  remixicon_updated: ^1.0.2
  # 权限处理
  permission_handler: ^11.0.1
  # 动画弹窗、动画按钮
  awesome_dialog: 3.0.2
  # 授予文件夹、安卓11及以上的文件操作
  shared_storage: ^0.8.0
  # 键值对存储
  shared_preferences: ^2.2.2
  # 应用操作
  device_apps: ^2.2.0
  # 底部导航栏
  salomon_bottom_bar: ^3.3.2
  # 分享
  share_plus: ^7.2.1
  # 电池信息
  battery_plus: ^4.1.0
  # 安卓intent操作
  android_intent_plus: ^4.0.3
  # 设备信息
  device_info_plus: ^9.1.0
  # 网络检查
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# 生成应用图标
flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/files/
    - assets/files/kjxg/
    - assets/files/zsxg/
    - assets/files/gyhxg/
    - assets/files/ddj/
    - assets/files/zdj/
    - assets/files/gdj/
