name: huazhixia
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 网络请求
  dio: ^5.1.2
  # 路由管理、状态管理
  get: ^4.6.5
  # remix图标库
  remixicon: ^1.0.0
  # toast提示
  oktoast: ^3.3.1
  # Uint8List的透明图像
  transparent_image: ^2.0.1
  # 设备信息
  device_info_plus: ^9.0.0
  # 电池信息
  battery_plus: ^4.0.0
  # 权限处理
  permission_handler: ^10.2.0
  # 弹窗、按钮
  awesome_dialog: ^3.0.2
  # 授予文件夹、安卓11+的文件操作
  shared_storage: ^0.7.1
  # 安卓intent操作
  android_intent_plus: ^4.0.0
  # 键值对存储
  shared_preferences: ^2.1.1
  # 应用操作
  device_apps: ^2.2.0
  # 分享
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/